snyk/cli-extension-sbom

.golangci.yaml
internal/mocks/service.go
internal/service/service.go
pkg/sbom/sbom.go

This refactors the workflow function to extract the API call portion to a `service` package.

refactor: move API call to service package

---

pkg/sbom/sbom.go

This documents additionally available SBOM output formats, such as CycloneDX XML and SPDX 2.3.

chore: add more available formats

---

pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This removes the default fallback to CycloneDX JSON as an output format and instead makes setting the format argument mandatory.

fix!: require a format from user

---

.golangci.yaml
internal/extension_errors/errors.go
internal/service/service.go
internal/service/service_test.go
pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This introduces a new internal Error type, `SBOMExtensionError`, which serializes to a customer facing message. This is considered an interim solution until we integrate with the error-catalog, which is still actively being explored for CLI Extensions.
The covered error cases are:
* user does not set `--experimental` flag (this will be removed soon, anyway)
* user does not set `--format`
* user sets wrong format

fix: improved user-facing error messages

---

pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This improves the error output the user sees when no organization id could be inferred.

fix: error when org ID could not be inferred

---

pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

Improves the error message when the invocation of the DepGraph workflow fails.

fix: improve error output when depgraph workflow fails

---

pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This improves the error output when extracting the payload data from the DepGraph workflow fails. In theory, this should only happen on rare occasions, if at all, so it's unlikely that users will see this on a regular basis. Still important to cover this case, though.

fix: better error msg when error handling data payloads

---

internal/extension_errors/errors.go
internal/mocks/service.go
internal/service/service.go
internal/service/service_test.go
pkg/sbom/sbom_test.go

This adds user-friendly error messages for unsuccessful API responses, such as
* 400 Bad Request
* 401 Unauthorized
* 403 Forbidden
* other non-200 codes

fix: better error messages for unsuccessful API responses

---

internal/service/service.go

This returns a user-friendly, generic internal error message when the reading of the API response body fails (which is not expected to happen regularly)

fix: better error msg when reading of response body fails

---

.circleci/config.yml

* Disables monitoring step after code test, as it monitors dependencies anyways, what we do after testing dependencies step

chore: do not monitor project twice

---

pkg/sbom/sbom.go

Introduces support for the following flags:
- `--all-projects`
- `--exclude`
- `name`
- `version`
Please note this PR introduces the update for the CLI to accept these flags but does not make use of them (follow up PR will address this)

feat(LINK-301): accept initial --all-project flags

---

internal/service/service.go
internal/service/service_test.go
pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This handles multiple depgraphs and sends them off to the conversion service. Alongside it sends a subject, which is required for hierarchical merging of the dependency graphs. Should no name for the subject be given (vie the `--name` flag) it falls back to the current working directory's name.

[LINK-323] feat: send multiple depgraphs

---

go.mod
go.sum
internal/flags/flags.go
internal/flags/flags_test.go
pkg/sbom/sbom.go

This PR adds support for the `--prune-repeated-subdependencies` flag and `--detection-depth` flag.
We also refactored flags into its own package and added a unit test.

feat: add additional flags with refactor and unit test

---

go.mod
go.sum
pkg/sbom/sbom.go

This fixes and issue with getting the current directory name. It was wrongly using the `path` package, which is not aware of Windows path separators, but rather only treats `/` as a separator. This has been fix by replacing it with the `path/filepath` package.

fix: use filepath pkg to get directory name

---

.golangci.yaml
go.mod
go.sum
pkg/sbom/sbom.go
pkg/sbom/sbom_test.go

This sets the `fail-fast` option of the DepGraphWorkflow when invoking with `all-projects`. This is to avoid incomplete SCA results if some manifest files cannot be analysed (in which case `snyk test` will silently skip over them).

[LINK-405] fix: fail SCA when generating for all projects

---

internal/service/service.go
internal/service/service_test.go
pkg/sbom/sbom.go

This commit adds functionality to the sbom service, allowing users to pass in a single depGraph *and* a subject that will be honored.
To achieve this, we simply send the multi-depgraph body with only one depGraph, and the subject with it.
Additionally, I've switched from using raw strings to construct the body-JSON to using `json.RawMessage` and proper types / structs. This also means that I've had to make the `Name` and `Version` fields of the `subject` type public. And to make the subject's usage easier in external packages, I've made the `Subject` type itself public as well.
`json.RawMessage` is nice because it can be used to tell Go that a certain field is already raw JSON, and has never been fully decoded into a custom type. As such, when marshaling JSON, that `RawMessage` is simply …

feat: single depGraph with subject

---

internal/flags/flags.go

Add support for [the maven specific args](https://docs.snyk.io/snyk-cli/commands/test#options-for-maven-projects) to this cli extension in order to make them available on the `snyk sbom` command.

feat: maven args support [LINK-692]

---

internal/flags/flags.go

Add support for [the gradle specific args](https://docs.snyk.io/snyk-cli/commands/test#options-for-gradle-projects) to this cli extension in order to make them available on the `snyk sbom` command.

feat: gradle args support

---

internal/flags/flags.go
internal/flags/flags_test.go

This adds additional config flags for ecosystems yarn and python:
*    `--yarn-workspaces`
*    `--command`
*    `--skip-unresolved`
*    `--package-manager`
See `snyk test --help` for details.

feat: add yarn, python flags

---

internal/flags/flags.go
internal/flags/flags_test.go

This PR adds additional config flags for nuget and npm ecosystems:
nuget
--assets-project-name 
--file=<filename>.sln
--file=packages.config
--packages-folder
npm
--strict-out-of-sync=true|false – Also works for Yarn, CocoaPods
See snyk test --help for details.

feat: add nuget + npm flags

---

internal/flags/flags.go

This adds additional config flag for unmanaged scanning:
`--max-depth`
See `snyk test --help` for details.

feat: unmanaged --max-depth arg support

---

internal/flags/flags.go
internal/flags/flags_test.go

A tiny type fix for the `assets-project-name` argument for NuGet.

fix: nuget assets-project-name

---

internal/flags/flags.go
internal/flags/flags_test.go

Fix the false scenario of the `strict-out-of-sync` argument on the NPM ecosystems.

fix: npm strict-out-of-sync arg

---

internal/service/service.go
internal/service/service_test.go
pkg/sbom/sbom_test.go

This adds formats `cyclonedx1.5+json`, `cyclonedx1.5+xml` to the CLI as available formats when generating SBOMs on the fly.

feat: add new formats for CycloneDX 1.5

---

go.mod
go.sum
internal/commands/sbomtest/presenter.go
internal/commands/sbomtest/presenter_test.go
internal/commands/sbomtest/sbomtest.go
internal/commands/sbomtest/testdata/snapshots/TestPresenter_JSON
internal/commands/sbomtest/testdata/snapshots/TestPresenter_Pretty

This adds a first presenter implementation to the `sbom test` command. The JSON format pretty much just encodes and prints a JSON string; the pretty format uses some string template and injects values. This is just a rough placeholder for the actual test results.

feat: add initial presenter for sbom test cmd

---

internal/commands/sbomtest/presenter_test.go
internal/commands/sbomtest/sbomloader.go
internal/commands/sbomtest/sbomloader_test.go
internal/commands/sbomtest/sbomtest.go
internal/commands/sbomtest/sbomtest_test.go
internal/commands/sbomtest/testdata/bom.json

This PR adds the ability to open and validate a SBOM via the `OpenSBOMFile` function.
The `OpenSBOMFile` will check for the following:
- The SBOM file exists
- The SBOM file is not a directory
- We have permission to open the SBOM file
- The SBOM file is a supported JSON SBOM file

feat: load sbom file

---

internal/snykclient/snykclient.go
internal/snykclient/snykclient_test.go

Updates the `SnykClient` to send the SBOM JSON wrapped in JSON:API.
This keeps the sending of the SBOM as an `io.Reader` rather than reading the file into memory to construct the JSON:API request. This is achieved by wrapping the JSON:API prefix & suffix bytes along with the SBOM JSON `io.Reader` in a `io.MultiReader`.

fix: send requests from sbomclient as JSON:API

---

internal/commands/sbomtest/presenter.go
internal/commands/sbomtest/presenter_test.go

This decouples the existing presenter tests from the SBOM test workflow command.

fix: decouple presenter tests

---

internal/snykclient/helpers.go
internal/snykclient/snykclient.go

Move `errFactory` one level up out of `parseResponse` function to catch all its errors under a `NewInternalError`. The motivation was catching some errors which were not wrapped i.e https://github.com/snyk/cli-extension-sbom/blob/9347cb700fdca8fd37af703147ccc28cea66c973/internal/snykclient/helpers.go#L17 and https://github.com/snyk/cli-extension-sbom/blob/9347cb700fdca8fd37af703147ccc28cea66c973/internal/snykclient/helpers.go#L32

feat: move errFactory out of parseResponse function

---

internal/commands/sbomtest/sbomtest.go
internal/errors/errors.go
internal/service/service.go
internal/snykclient/snykclient.go
internal/snykclient/snykclient_test.go

Use the appropriate error messages for the `sbom test` command, and rename the generation error variables to include the context.

fix: error messages

---

internal/commands/sbomtest/sbomloader.go
internal/commands/sbomtest/sbomloader_test.go
internal/commands/sbomtest/sbomtest_test.go
internal/errors/errors.go

Saw that when given an invalid filepath, error message says there was no filepath given at all. Also, fixed a typo.

wip: improvements in file error handling

---

internal/errors/errors.go

This adds `SBOMExtensionError.Unwrap() error`

fix: unwrap underlying error of SBOMExtensionError

---

internal/view/issues.go
internal/view/issues_test.go
internal/view/summary.go
internal/view/testdata/snapshots/Test_generateIssues
internal/view/testresult.go
internal/view/untested.go

Unescapes the vulnerability titles, by rendering the pretty results using `text/template` package instead of `html/template`.
[https://snyksec.atlassian.net/browse/UNIFY-223](UNIFY-223)

fix: unescape vulnerability titles

---

internal/commands/sbomcreate/sbomcreate_test.go
internal/service/service.go
internal/service/service_test.go

Extends the list of accepted SBOM formats to include `CycloneDX 1.6`

add: cyclonedx 1.6 support

---

internal/flags/flags.go

This adds support for the `--gradle-normalize-deps` flag to get forwarded to the DepGraph workflow.

feat: add support for --gradle-normalize-deps

---

internal/snykclient/monitordeps.go
internal/snykclient/monitordeps_test.go
internal/snykclient/types.go

Client function to send `ScanResult` to monitor dependencies endpoint.

feat: Submit scan results to registry

---

internal/snykclient/monitordeps.go
internal/snykclient/sbomconvert.go
internal/snykclient/sbomconvert_test.go
internal/snykclient/types.go

A client to convert an SBOM into an array of `ScanResult`s.

feat: convert SBOM into scan results

---

internal/snykclient/monitordeps.go
internal/snykclient/monitordeps_test.go
internal/snykclient/sbomconvert.go
internal/snykclient/types.go

Adds methods to augment a ScanResult with target name, target reference and a Snyk Policy.
These are needed to process a `ScanResult` coming from the upstream request and add additional information from the client-side environment.

feat: add methods to augment ScanResult

---

internal/view/sbommonitor/init_test.go
internal/view/sbommonitor/monitor.go
internal/view/sbommonitor/monitor_test.go
internal/view/sbommonitor/project.go
internal/view/sbommonitor/project_test.go
internal/view/sbommonitor/render.go
internal/view/sbommonitor/render_test.go
internal/view/sbommonitor/style.go
internal/view/sbommonitor/testdata/snapshots/TestRenderMonitor
internal/view/sbommonitor/testdata/snapshots/TestRenderMonitor_MultipleProjects
internal/view/sbommonitor/testdata/snapshots/Test_generateMonitorProject
internal/view/sbommonitor/testdata/snapshots/Test_generateMonitor_multipleProjects
internal/view/sbommonitor/testdata/snapshots/Test_generateMonitor_oneProject

Show the cli user what projects have been monitored and where to find them.
- Output is in the same style as the existing `snyk monitor` command.
- The tests assert key information is present while ignoring presentation style.

feat: render the output similar to a std monitor

---

internal/commands/sbommonitor/sbommonitor.go
internal/errors/errors.go
internal/snykclient/monitordeps.go
internal/snykclient/sbomconvert.go
internal/snykclient/sbomconvert_test.go

Uses the error factory to print meaningful error messages. This is the precursor to a follow-up PR where we also print errors in case monitoring of a single dep-graph fails (in the loop, now a TODO comment).

feat: handle errors during monitor sub-command

---

internal/commands/sbommonitor/sbommonitor.go
internal/view/sbommonitor/render.go
internal/view/sbommonitor/render_test.go
internal/view/sbommonitor/template.go
internal/view/sbommonitor/testdata/snapshots/TestRenderer_RenderMonitor
internal/view/sbommonitor/testdata/snapshots/TestRenderer_RenderMonitor_WithError

Renders the details of an error when monitoring fails (single request to Registry).
This is mostly a "beta" version, since:
* we don't have any good design for this
* the copy isn't vetted
* we'd likely like to include a request ID, coming in a future PR

feat: render successes and errors during monitoring

---

internal/snykclient/monitordeps.go
internal/snykclient/monitordeps_test.go

This handles different permutations of error responses from the v1 API and attempts to turn them into a human-readable string we can use on screen.

fix: handle error responses from the v1 API

---

internal/commands/sbommonitor/sbommonitor.go

Tiny fix where we forgot to close the file descriptor that we open for the SBOM file.

fix: close the input file descriptor when done

---

internal/snykclient/helpers.go
internal/snykclient/monitordeps.go
internal/snykclient/monitordeps_test.go
internal/snykclient/sbomconvert.go

This PR adds support for including the `snyk-request-id` in error messages received from Snyk services. This will help with debugging issues during the closed beta.
- This is a minimal implementation to expose the request ID to users.
- In future iterations:
- These errors will be mapped to entries in the error catalogue.
- The `go-application-framework` will be used to standardise showing the error along with the request ID.

Show Snyk RequestId for server errors

---

internal/commands/sbommonitor/sbommonitor.go
internal/commands/sbommonitor/sbommonitor_test.go
internal/commands/sbommonitor/testdata/bom.json
internal/commands/sbommonitor/testdata/registry-monitor-dependencies.response.json
internal/commands/sbommonitor/testdata/sbom-test-convert.response.json
internal/errors/errors.go

- Add tests for SBOM Monitor command
- Require the `--remote-repo-url` flag to be set

feat: require remote repo url flag

---

internal/commands/sbommonitor/sbommonitor_test.go

Cleaning up a bit of copy pasta in our sbom monitor command test.

chore: clean up test setup

---

internal/commands/sbommonitor/sbommonitor.go
internal/commands/sbommonitor/sbommonitor_test.go
internal/commands/sbommonitor/testdata/sbom-test-convert-no-results.response.json
internal/errors/errors.go

This introduces a new error which will be returned if no supported projects were found in the SBOM when doing an `snyk sbom monitor`.

feat(monitor): return an error when no supported projects were found

---

internal/bundlestore/client.go
internal/bundlestore/config.go
internal/bundlestore/encoding.go
internal/bundlestore/utils.go
internal/commands/sbomcreate/sbomcreate_test.go
internal/commands/sbomtest/sbomtest.go
internal/commands/sbomtest/sbomtest_test.go
internal/sbom/loader_test.go
internal/service/service.go
internal/service/service_test.go
internal/snykclient/snykclient_test.go

This PR fixes linting errors and unit test failures in the `wip/reachability` branch, and adds a boolean flag which looks up an environment variable to guard the new code path. This will allow us to merge the feature branch into main without exposing any of the functionality (unless users have dug through the source code and know about the feature flag but we think this is an okay approach - we're waiting on confirmation [here](https://snyk.slack.com/archives/C073HFTPLSF/p1744642155947399)).

fix: fix linting errors and add flag to hide reachability

---

internal/commands/sbommonitor/sbommonitor.go
internal/commands/sbommonitor/sbommonitor_test.go
internal/snykclient/sbomconvert.go
internal/snykclient/sbomconvert_test.go

This makes the `remote_repo_url` (target identity) part of the SBOM conversion request, so that it can be used as a fallback value when constructing project identities.

feat: send remote_repo_url during SBOM conversion

---

internal/commands/sbomtest/sbomtest_reachability_test.go

This PR adds an initial test for the new reachability path, to ensure that the Bundlestore endpoints are called correctly.

test: add tests for uploading SBOM

---

internal/cmd_exec/cmd_exec.go
internal/cmd_exec/cmd_exec_test.go

Removes the git origin sanitisation logic since this will now be done on the server side.

chore: remove git origin sanitisation logic

---

internal/commands/sbomtest/sbomtest.go
internal/commands/sbomtest/sbomtest_reachability_test.go

Updates the environment variable guarding the reachability work based on the guidance [here](https://snyk.slack.com/archives/C073HFTPLSF/p1744737767059279?thread_ts=1744642155.947399&cid=C073HFTPLSF):
- Adds `INTERNAL_` prefix
- Uses `config.GetBool` instead of `os.Getenv`

chore: update env var name

---

internal/service/service_test.go

For some reason (I think thanks to Rancher desktop listening on some ports) the `TestDepGraphsToSBOM_FailedRequest` was failing for me locally, as I was getting a 404 compared to `dial tcp 0.0.0.0:80: connect: connection refused` which was happening in CI. This modification ensures that the test works both on CI and locally, by forcing the server to fail the request rather than just hoping that nothing is listening on the URL passed in.

fix: resolve mismatch between test running in CI and locally

---

internal/bundlestore/client.go
internal/bundlestore/config.go
internal/bundlestore/encoding.go
internal/bundlestore/utils.go

In [this PR](https://github.com/snyk/cli-extension-sbom/pull/133/files) I incorrectly referred to `go-application-framework` in some comments about the origin of the bundlestore code - in fact we copied this code from `code-client-go`.

chore: fix comments incorrectly referencing GAF

---

internal/bundlestore/client.go

When uploading the SBOM in a FedRamp environment we should use the snyk api instead of the deeproxy one, as seen [in code-client-go](https://github.com/snyk/code-client-go/blob/d8776ec05eeba7019489212f4a62f91ed51673d5/internal/deepcode/client.go#L184).

feat(reachability): use snyk api for uploading SBOMs in fedramp env

---

internal/commands/sbomtest/sbomtest.go
internal/commands/sbomtest/sbomtest_test.go
internal/flags/flags.go

Adds missing flags that need to be passed down to the `cli-extension-os-flows` test command.

feat(reachability): add missing os flows flags
